[connections.my_database]
    type="sql"
    dialect="mysql"
    username="dashboard"
    password="19DHisddS!59!"
    host="81.7.10.99" # IP or URL
    port=3306 # Port number
    database="home-dashboard" # Database name